apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-spring-boot
  namespace: default
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-spring-boot
  template:
    metadata:
      labels:
        app: hello-world-spring-boot
    spec:
      containers:
      - name: hello-world-spring-boot
        image: hello-world-spring-boot:1.0
        ports:
        - containerPort: 8080