apiVersion: apps/v1
kind: Service
metadata:
  name: hello-world-spring-boot
  namespace: default
spec:
  selector:
    app: hello-world-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer